<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>ScientificCalculator</AssemblyName>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>ScientificCalculator</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
